FROM alpine:3.10

LABEL version="1.0.0"
LABEL maintainer="Pendect Tech Team <tech@pendect.com>" \
      org.label-schema.vendor="Pendect GmbH" \
      com.github.actions.name="Rsync GitHub Action" \
      com.github.actions.description="This action syncs files (probably) generated by a previous step in the workflow with a remote server." \
      com.github.actions.icon="copy" \
      com.github.actions.color="blue"

RUN apk add --no-cache --virtual .run-deps rsync openssh && \
    rm -rf /var/cache/apk/*

COPY entrypoint.sh /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
