name: Lint files

on: push

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: Lint shell file
        uses: azohra/shell-linter@latest
        with:
          path: "entrypoint.sh"

      - name: Lint Dockerfile
        uses: brpaz/hadolint-action@v3.0.0
        with:
          dockerfile: "Dockerfile"
